# Generated by Django 3.0 on 2022-03-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images5',
        ),
        migrations.AlterField(
            model_name='product',
            name='images1',
            field=models.ImageField(upload_to=''),
        ),
    ]
