# Generated by Django 3.0 on 2022-03-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_auto_20220330_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
